### ISSUE TITLE
Question: How is Pimcore actually installed?

### ISSUE THREAD

**Issue by mingfang** [dpfaffenbauer/pimcore-docker#10]
I searched through all the Dockerfiles here and do not see where and how Pimcore is installed.
I have my own Dockerfile here https://github.com/mingfang/docker-pimcore and am trying to compare with yours.
The main challenge I still have is to figure out how to automate the install and upgrade since I have to run the install cmd manually now.

**Comment by dpfaffenbauer** [comment]
Its not. I don't need Pimcore to be installed automatically in the container. This containers are supposed for DEV only, and you need to run the install command manually.
