### ISSUE TITLE
[Feature] Add WebP support

### ISSUE THREAD

**Issue by aarongerig** [dpfaffenbauer/pimcore-docker#11]
As WebP thumbnail generation was introduced with Pimcore 5.5, this docker image should install Imagick with WebP support as well. Probably would speed up loading thumbnails quite a bit on WebP supporting browsers.

**Comment by dpfaffenbauer** [comment]
How did Pimcore implement that? What binary is necessary for that? Would it also be possible for you to create a PR?

**Comment by aarongerig** [comment]
https://github.com/pimcore/pimcore/commit/9abfc484d0a17516bd4c65cf336c59a6a510ec1d

https://github.com/pimcore/pimcore/commit/5c255dfacf1ee830c5bc511d1be55510548c7662

If I figure it out how to install Imagick with the WebP binary in a Dockerfile, I could definitely provide a PR.

**Comment by aarongerig** [comment]
Cool, thanks!

**Comment by dpfaffenbauer** [comment]
Images are currently building, I actually had no chance to test it, could you please do? Build should be finished within an hour or two:

https://hub.docker.com/r/dpfaffenbauer/pimcore/builds/

**Comment by aarongerig** [comment]
@dpfaffenbauer Works just as expected! 👍
