### ISSUE TITLE
Some checks fail on 7.3 images

### ISSUE THREAD

**Issue by Ben305** [dpfaffenbauer/pimcore-docker#19]
I recently switched from the apache-7.2 image to the apache-7.3 image. Some Pimcore system environment checks now fail:

- zip
- Imagick
- APCu
- Redis
- WebP

All these checks pass when using the 7.2 image.

**Comment by dpfaffenbauer** [comment]
that is fixed now, but builds take forever to finish.... docker hub is quite slow building them. Should be available tomorrow.
