### ISSUE TITLE
Noob question - how to use this container

### ISSUE THREAD

**Issue by paulschmeida** [dpfaffenbauer/pimcore-docker#23]
Hi. I'm a bit of a docker noob. All the containers that I've worked with were set up from the start and I could simple access the web interface of whatever I've pulled and run. 
These containers don't seem to have any ports mapped to the outside and there's no documentation. 
Are these just base images that I'm supposed to use to install Pimcore on myself? Are there any guides available? 
Some basic information would be nice to point new users in the right direction.

**Comment by dpfaffenbauer** [comment]
use https://github.com/dpfaffenbauer/pimcore-skeleton/releases/tag/6.0.1

Run

```bash
docker-compose up -d
docker-compose exec php bash

# in the container
vendor/bin/pimcore-install --mysql-host-socket=db
```

Visit: localhost:2000/admin

Thats sort of it actually.

The container images don't contain pimcore for a reason.
