### ISSUE TITLE
Dockerhub images down

### ISSUE THREAD

**Issue by schliflo** [dpfaffenbauer/pimcore-docker#8]
Seems like you took the off there: https://hub.docker.com/r/dpfaffenbauer/pimcore-docker-php-fpm/
Could you elaborate on the reasoning? I found them quite handy.

**Comment by dpfaffenbauer** [comment]
I moved them here https://hub.docker.com/r/dpfaffenbauer/pimcore/, but docker hub has no feature to rename them.

**Comment by schliflo** [comment]
Thx, just found out myself :)

**Comment by mayouf** [comment]
Hi,

I typed `docker pull dpfaffenbauer/pimcore`

It is not working. Here is the Error message:

> Error response from daemon: manifest for dpfaffenbauer/pimcore:latest not found

Any tips ?

**Comment by dpfaffenbauer** [comment]
You have to provide a specific tag, there is no "default" on those images. Try it like:

```docker pull dpfaffenbauer/pimcore:PHP7.3-fpm```
