### ISSUE TITLE
Composer not usable

### ISSUE THREAD

**Issue by schliflo** [dpfaffenbauer/pimcore-docker#9]
I only tested this in the `PHP7.2-apache` image but I suspect it's a general issue. Despite the installation seemingly being [correct in the Dockerfile](https://github.com/dpfaffenbauer/pimcore-docker/blob/master/PHP7.2-apache/Dockerfile#L76) composer is not usable. As you can see it's nowhere to be found.
```bash
$ docker run --rm dpfaffenbauer/pimcore:PHP7.2-apache ls /usr/local/bin
Magick++-config
MagickCore-config
MagickWand-config
animate
apache2-foreground
compare
composite
conjure
convert
display
docker-php-entrypoint
docker-php-ext-configure
docker-php-ext-enable
docker-php-ext-install
docker-php-source
f2py
facedetect
identify
import
magick
magick-script
mogrify
montage
pear
peardev
pecl
phar
phar.phar
php
php-config
phpdbg
phpize
stream
```
```bash
$ docker run --rm dpfaffenbauer/pimcore:PHP7.2-apache which composer
```

**Comment by dpfaffenbauer** [comment]
composer is here: ```/usr/local/bin/composer``` and it works for me

**Comment by schliflo** [comment]
can you please re-check this?
```shell
$ docker pull dpfaffenbauer/pimcore:PHP7.2-apache
PHP7.2-apache: Pulling from dpfaffenbauer/pimcore
Digest: sha256:5ea91125ea4f815c81590f1095cd56020be72522278ec7189607278ebdfaa3ef
Status: Image is up to date for dpfaffenbauer/pimcore:PHP7.2-apache

$ docker run --rm dpfaffenbauer/pimcore:PHP7.2-apache ls /usr/local/bin
Magick++-config
MagickCore-config
MagickWand-config
animate
apache2-foreground
compare
composite
conjure
convert
display
docker-php-entrypoint
docker-php-ext-configure
docker-php-ext-enable
docker-php-ext-install
docker-php-source
f2py
facedetect
identify
import
magick
magick-script
mogrify
montage
pear
peardev
pecl
phar
phar.phar
php
php-config
phpdbg
phpize
stream
```

Seems like I'm on the latest image and it's certainly not there for me

**Comment by dpfaffenbauer** [comment]
you are right, but it seems to be a problem with 7.2 only. I triggered a new build on docker hub.

https://hub.docker.com/r/dpfaffenbauer/pimcore/builds/boqgyzsl2cvmemgm6hzfk9c/

**Comment by dpfaffenbauer** [comment]
there is something else off with that image as well.... doesn't even boot up properly

**Comment by dpfaffenbauer** [comment]
ok, guess I found the issue. Build process is triggered, takes some time to build though.

**Comment by dpfaffenbauer** [comment]
this is fixed now. debug images still are being created, but the default PHP7.2-apache works now
